import {z} from 'zod';
import type {components} from '@/generated/api-types';
import {authenticatedFetch} from '@/shared/api/authenticated';
export type Report=components['schemas']['Report'];
const source=z.strictObject({materialId:z.uuid(),lineStart:z.number().int().positive(),lineEnd:z.number().int().positive(),quotedText:z.string()});
const observation=z.strictObject({id:z.uuid(),kind:z.enum(['SOURCE_CHECK','FAULT_REPAIR','COUNTEREVIDENCE','CHANGE_RESPONSE','EXPLANATION','PROMPT_REVISION','SELF_REPORT']),polarity:z.enum(['SUPPORT','CONTRADICT']),method:z.enum(['RULE','LLM']),subjectType:z.enum(['DOCUMENT_VERSION','FAULT_ATTEMPT']),subjectId:z.uuid(),excerpt:z.string().nullable(),explanation:z.string(),source:source.nullable()});
const dimension=z.strictObject({code:z.string(),title:z.string(),state:z.enum(['SUFFICIENT','PARTIAL','NEEDS_REVIEW','NOT_OBSERVED']),rationale:z.string(),gap:z.string().nullable(),nextAction:z.string().nullable(),confidenceLevel:z.enum(['LOW','MEDIUM','HIGH']).nullable(),evidence:z.array(observation)});
// F05b publishes INITIAL only. Final comparison and additional evidence subjects remain unsupported.
export const reportSchema:z.ZodType<Report>=z.strictObject({id:z.uuid(),sessionId:z.uuid(),evaluationId:z.uuid(),phase:z.literal('INITIAL'),documentVersionId:z.uuid(),sample:z.boolean(),summary:z.string(),strengths:z.array(z.string()),improvements:z.array(z.string()),areas:z.array(z.strictObject({area:z.enum(['PROMPT','EVIDENCE','DOCUMENT','DEFENSE']),dimensions:z.array(dimension).min(1)})).length(4),faultSummary:z.strictObject({note:z.string(),statements:z.array(z.strictObject({statementId:z.uuid(),reviewId:z.uuid().nullable(),detectionResult:z.enum(['DETECTED','MISSED','FALSE_POSITIVE','VALID_KEEP','UNREVIEWED','REVIEW_REQUIRED']),evidenceResult:z.enum(['SUPPORTED','INSUFFICIENT','NOT_OBSERVED','REVIEW_REQUIRED']),repairResult:z.enum(['VALID','INVALID','NOT_APPLICABLE','NOT_OBSERVED','REVIEW_REQUIRED']),recheckResult:z.enum(['OBSERVED','NOT_OBSERVED','REVIEW_REQUIRED']),feedback:z.string()}))}),comparison:z.null(),nextPracticeText:z.string().nullable(),createdAt:z.iso.datetime({offset:true})});
export const getReport=(id:string,signal?:AbortSignal)=>authenticatedFetch(`/reports/${id}`,reportSchema,{signal,cache:'no-store'});
