import {test,expect} from '@playwright/test';
import {testIdentity,installTestSession,apiBase} from '../support/e2e-auth';
const fixed='function addItem(items,item){return items.some(x=>x.id===item.id)?items.slice():[...items,item];}';
test('code practice executes real code, persists results, restores and seals submission',async({page,context,request},info)=>{
 page.on('console',m=>{if(m.text().includes('CODING_WORKER_INIT'))console.log(m.text());});
 const identity=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,identity.session);
 await page.goto('/coding');await page.getByRole('button',{name:'새 구현 과제 시작'}).click();
 await expect(page).toHaveURL(/\/coding\/[0-9a-f-]+$/);
 await page.getByRole('button',{name:'저장하고 테스트'}).click();
 await expect(page.getByText('실패 · 같은 id 중복 방지')).toBeVisible();
 await expect(page.getByText('실패 · 원본 배열 보존')).toBeVisible();
 await expect(page.getByText(/예상: 항목 1개 \(a · 기존\)/).first()).toBeVisible();
 await expect(page.getByText(/\[\{"id"/)).toHaveCount(0);
 await page.getByRole('textbox',{name:'AI에게 요청',exact:true}).fill('실패 원인을 설명하고 수정해 줘');
 await page.getByRole('button',{name:'질문 보내기',exact:true}).click();
 await expect(page.getByRole('main').getByRole('alert')).toContainText('AI 연결이 설정되지 않았습니다');
 await page.getByRole('textbox',{name:'solution.js'}).fill(fixed);
 await page.getByRole('button',{name:'저장하고 테스트'}).click();
 await expect(page.getByText('통과 · 같은 id 중복 방지')).toBeVisible();
 await expect(page.getByText('통과 · 원본 배열 보존')).toBeVisible();
 await page.reload();await expect(page.getByRole('textbox',{name:'solution.js'})).toHaveValue(fixed);
 await expect(page.getByText('통과 · 같은 id 중복 방지')).toBeVisible();
 await page.getByRole('textbox',{name:'구현과 검증 설명'}).fill('id로 중복을 확인하고 새 배열을 반환했습니다. 네 가지 공개 테스트를 실행했습니다.');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'최종 코드 제출'}).click();
 await expect(page.getByText('제출 완료 · 읽기 전용')).toBeVisible();
 await expect(page.getByRole('textbox',{name:'solution.js'})).toBeDisabled();
 const id=page.url().split('/').at(-1);const bob=await testIdentity(request,'bob');
 expect((await request.get(`${apiBase}/coding-workspaces/${id}`,{headers:bob.headers})).status()).toBe(404);
 await page.setViewportSize({width:375,height:850});
 await page.getByRole('button',{name:'편집기 크게 보기'}).click();await expect(page.getByRole('button',{name:'편집기 닫기'})).toBeVisible();await page.getByRole('button',{name:'편집기 닫기'}).click();
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('coding-mobile.png'),fullPage:true});
});
test('infinite loop is interrupted and the editor remains usable',async({page,context,request})=>{
 page.on('console',m=>{if(m.text().includes('CODING_WORKER_INIT'))console.log(m.text());});
 const identity=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,identity.session);
 await page.goto('/coding');await page.getByRole('button',{name:'새 구현 과제 시작'}).click();
 await page.getByRole('textbox',{name:'solution.js'}).fill('while(true){}');
 await page.getByRole('button',{name:'저장하고 테스트'}).click();
 await expect(page.getByText('실패 · 새 항목 추가')).toBeVisible({timeout:15000});
 await page.getByRole('textbox',{name:'solution.js'}).fill(fixed);
 await page.getByRole('button',{name:'저장하고 테스트'}).click();
 await expect(page.getByText('통과 · 새 항목 추가')).toBeVisible();
});
