import {test,expect} from '@playwright/test';
import {apiBase,installTestSession,testIdentity} from '../support/e2e-auth';
for(const kind of ['REPORT','CODING'])for(const mode of ['TRAINING','SIMULATION'])test(`learning ${kind} ${mode}: real save, verification, explanation, failure and restore`,async({page,context,request})=>{
 const browserErrors:string[]=[];page.on('pageerror',e=>browserErrors.push(e.message));const who=await testIdentity(request);await installTestSession(context,who.session);
 const created=await request.post(`${apiBase}/learning-flows`,{headers:who.headers,data:{requestKey:crypto.randomUUID(),kind,mode}});expect(created.ok()).toBeTruthy();const f=await created.json();await page.goto(`/learn/${f.id}`);
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();
 if(mode==='TRAINING'){await page.getByText('필요할 때만 힌트 보기',{exact:true}).click();await page.getByRole('button',{name:'힌트 1',exact:true}).click();await expect(page.getByText(kind==='REPORT'?'자료에서 확인된 사실과 아직 모르는 것을 먼저 나눠 보세요.':'먼저 시작 코드를 실행하고 어떤 요구사항이 실패하는지 확인해 보세요.',{exact:true})).toBeVisible();}else await expect(page.getByRole('button',{name:'힌트 1',exact:true})).toHaveCount(0);
 if(kind==='REPORT'){await page.getByLabel('보고서 내용',{exact:true}).fill('10:00 지연이 관찰됐지만 원인은 미확인이다. 연결 대기와 외부 응답 시간을 확인해야 한다.');await expect(page.getByText('저장됨',{exact:true})).toBeVisible();}else{await page.getByLabel('solution.js',{exact:true}).fill('function addItem(items,item){return items.some(x=>x.id===item.id)?items.slice():[...items,item];}');await page.getByRole('button',{name:'저장하고 테스트',exact:true}).click();await expect(page.getByText('통과 · 같은 id 중복 방지')).toBeVisible();}
 await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();
 if(kind==='REPORT')await page.getByRole('button',{name:'근거 연결',exact:true}).click();
 await page.getByLabel('채택한 방법과 남은 한계',{exact:true}).fill('확인 가능한 범위만 판단했다. 추가 검증이 필요하다.');await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).fill('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');await page.getByRole('button',{name:'검증 설명 저장',exact:true}).click();await page.reload();await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');
 await page.screenshot({path:test.info().outputPath('working.png'),fullPage:true});
 page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'결과물 제출하고 직접 설명하기',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'결과물 제출하고 직접 설명하기',exact:true}).click();await expect(page.getByRole('heading',{name:'내 판단을 직접 설명하기',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'질문 보내기',exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'AI에게 요청하기',exact:true})).toHaveCount(0);await expect(page.getByText('검산 초안',{exact:true})).toHaveCount(0);
 await page.reload();await page.locator('#decision').fill('설명하기 어려운 부분이 있으며 추가 검증이 필요하다.');await page.locator('#change').fill('달라진 조건에 맞춰 근거와 테스트를 다시 확인하겠다.');await page.getByRole('button',{name:'직접 설명 제출',exact:true}).click();await expect(page.getByRole('heading',{name:'근거 중심 피드백',exact:true})).toBeVisible();await page.getByRole('button',{name:'근거 중심 피드백 받기',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'평가 AI가 설정되지 않았습니다'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'결과물과 검증 기록',exact:true})).toBeVisible();
 await page.screenshot({path:test.info().outputPath('feedback-awaiting.png'),fullPage:true});expect(browserErrors).toEqual([]);
 const bob=await testIdentity(request,'bob');expect((await request.get(`${apiBase}/learning-flows/${f.id}`,{headers:bob.headers})).status()).toBe(404);
});
test('learning catalog exposes both task types and modes on a narrow screen',async({page,context,request})=>{const who=await testIdentity(request);await installTestSession(context,who.session);await page.setViewportSize({width:375,height:850});await page.goto('/learn');await expect(page.getByRole('button',{name:'보고서 과제 시작',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'구현 과제 시작',exact:true})).toBeVisible();await page.getByLabel('과제 모드').selectOption('SIMULATION');await page.getByRole('button',{name:'구현 과제 시작',exact:true}).click();await expect(page).toHaveURL(/\/learn\/[0-9a-f-]+$/);await page.getByRole('button',{name:'2. 작업',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:test.info().outputPath('mobile.png'),fullPage:true});});

test('guided work preserves drafts across desktop/mobile panels and does not submit on navigation',async({page,context,request})=>{
 const who=await testIdentity(request);await installTestSession(context,who.session);
 const res=await request.post(`${apiBase}/learning-flows`,{headers:who.headers,data:{requestKey:crypto.randomUUID(),kind:'CODING',mode:'TRAINING'}});expect(res.ok()).toBeTruthy();const flow=await res.json();
 await page.goto(`/learn/${flow.id}`);await expect(page.getByLabel('훈련 안내')).toContainText('시작 코드를 테스트');
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();await page.getByLabel('solution.js',{exact:true}).fill('// unsaved draft');await page.getByLabel('AI에게 요청',{exact:true}).fill('아직 전송하지 않은 질문');
 await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).fill('아직 저장하지 않은 설명');
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toHaveValue('// unsaved draft');await expect(page.getByLabel('AI에게 요청',{exact:true})).toHaveValue('아직 전송하지 않은 질문');
 const panel=page.getByLabel('결과물 패널',{exact:true});const scroll=await panel.evaluate(e=>{e.scrollTop=90;return e.scrollTop;});expect(scroll).toBeGreaterThan(0);
 await page.getByRole('button',{name:'1. 과제 이해',exact:true}).click();await page.getByRole('button',{name:'2. 작업',exact:true}).click();expect(await panel.evaluate(e=>e.scrollTop)).toBe(scroll);
 await panel.evaluate(e=>{e.scrollTop=0;});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('desktop-work.png'),fullPage:true});
 await page.setViewportSize({width:375,height:850});await page.getByRole('navigation',{name:'작업 패널 선택'}).getByRole('button',{name:'AI 대화',exact:true}).click();await expect(page.getByLabel('AI에게 요청',{exact:true})).toHaveValue('아직 전송하지 않은 질문');await expect(page.getByLabel('solution.js',{exact:true})).not.toBeVisible();
 await page.getByRole('navigation',{name:'작업 패널 선택'}).getByRole('button',{name:'내 결과물',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toHaveValue('// unsaved draft');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.evaluate(()=>window.scrollTo(0,400));const header=await page.locator('header').boundingBox();const stages=await page.getByRole('navigation',{name:'단계 이동'}).boundingBox();expect(stages!.y).toBeGreaterThanOrEqual(header!.y+header!.height-1);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('mobile-work.png'),fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('아직 저장하지 않은 설명');
 expect(await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).evaluate(e=>{let n:HTMLElement|null=e;while(n){if(getComputedStyle(n).animationName!=='none')return false;n=n.parentElement;}return true;})).toBeTruthy();
 expect((await (await request.get(`${apiBase}/learning-flows/${flow.id}`,{headers:who.headers})).json()).stage).toBe('WORKING');
});
