import {test,expect} from '@playwright/test';
import {apiBase,installTestSession,testIdentity} from '../support/e2e-auth';
for(const kind of ['REPORT','CODING'])for(const mode of ['TRAINING','SIMULATION'])test(`learning ${kind} ${mode}: real save, verification, explanation, failure and restore`,async({page,context,request})=>{
 const browserErrors:string[]=[];page.on('pageerror',e=>browserErrors.push(e.message));const who=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,who.session);
 const created=await request.post(`${apiBase}/learning-flows`,{headers:who.headers,data:{requestKey:crypto.randomUUID(),kind,mode}});expect(created.ok()).toBeTruthy();const f=await created.json();await page.goto(`/learn/${f.id}`);
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();if(kind==='REPORT')await page.getByRole('navigation',{name:'참고 패널 선택'}).getByRole('button',{name:'AI 대화',exact:true}).click();const artifactPanel=page.getByLabel('결과물 패널',{exact:true});const assistantPanel=page.getByLabel('AI 대화 패널',{exact:true});const artifactBox=await artifactPanel.boundingBox();const assistantBox=await assistantPanel.boundingBox();expect(artifactBox!.x).toBeLessThan(assistantBox!.x);if(kind==='REPORT'){const reportCard=page.getByRole('heading',{name:'내 보고서',exact:true}).locator('xpath=ancestor::section[1]');const reportBox=await reportCard.boundingBox();expect(Math.abs(reportBox!.height-artifactBox!.height)).toBeLessThanOrEqual(1);}
 if(mode==='TRAINING'){await page.getByRole('tab',{name:/사실과 미확인 구분|실패부터 확인/}).click();await expect(page.getByText(kind==='REPORT'?'자료에서 확인된 사실과 아직 모르는 것을 먼저 나눠 보세요.':'먼저 시작 코드를 실행하고 어떤 요구사항이 실패하는지 확인해 보세요.',{exact:true})).toBeVisible();if(kind==='REPORT'){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('hint-cards.png'),fullPage:true});}}else await expect(page.getByRole('tab',{name:/사실과 미확인 구분|실패부터 확인/})).toHaveCount(0);
 if(kind==='REPORT'){await page.getByLabel('보고서 내용',{exact:true}).fill('10:00 지연이 관찰됐지만 원인은 미확인이다. 연결 대기와 외부 응답 시간을 확인해야 한다.');await expect(page.getByText('저장됨',{exact:true})).toBeVisible();}else{await page.getByLabel('solution.js',{exact:true}).fill('function addItem(items,item){return items.some(x=>x.id===item.id)?items.slice():[...items,item];}');await page.getByRole('button',{name:'저장하고 테스트',exact:true}).click();await expect(page.getByText('통과 · 같은 id 중복 방지')).toBeVisible();}
 await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();
 if(kind==='REPORT'){await page.getByRole('button',{name:/1.*10:00 결제 API p95/}).click();await page.getByRole('button',{name:'이 원문 연결하기',exact:true}).click();await expect(page.getByLabel('1번째 근거 삭제')).toBeVisible();if(mode==='TRAINING'){await page.getByRole('heading',{name:'보고서에 사용한 근거',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:test.info().outputPath('evidence-picker.png')});}}
 await page.getByLabel('채택한 방법과 남은 한계',{exact:true}).fill('확인 가능한 범위만 판단했다. 추가 검증이 필요하다.');await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).fill('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');await page.getByRole('button',{name:'검증 설명 저장',exact:true}).click();await page.reload();await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');
 await page.screenshot({path:test.info().outputPath('working.png'),fullPage:true});
 page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'결과물 제출하고 직접 설명하기',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('요구사항과 관찰 결과를 대조했다. 확인하지 못한 부분은 남겨두었다.');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'결과물 제출하고 직접 설명하기',exact:true}).click();await expect(page.getByRole('heading',{name:'내 판단을 직접 설명하기',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'질문 보내기',exact:true})).toHaveCount(0);await expect(page.getByRole('log',{name:'AI 대화 기록',exact:true})).toHaveCount(0);await expect(page.getByText('검산 초안',{exact:true})).toHaveCount(0);
 await page.reload();await page.locator('#decision').fill('설명하기 어려운 부분이 있으며 추가 검증이 필요하다.');await page.locator('#change').fill('달라진 조건에 맞춰 근거와 테스트를 다시 확인하겠다.');await page.getByRole('button',{name:'직접 설명 제출',exact:true}).click();await expect(page.getByRole('heading',{name:'근거 중심 피드백',exact:true})).toBeVisible();await page.getByRole('button',{name:'근거 중심 피드백 받기',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'평가 AI가 설정되지 않았습니다'})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'결과물과 검증 기록',exact:true})).toBeVisible();
 await page.screenshot({path:test.info().outputPath('feedback-awaiting.png'),fullPage:true});expect(browserErrors).toEqual([]);
 const bob=await testIdentity(request,'bob');expect((await request.get(`${apiBase}/learning-flows/${f.id}`,{headers:bob.headers})).status()).toBe(404);
});
test('learning catalog exposes both task types and modes on a narrow screen',async({page,context,request})=>{const who=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,who.session);await page.setViewportSize({width:375,height:850});await page.goto('/learn');await expect(page.getByRole('link',{name:'AI 과제 훈련',exact:true})).toHaveAttribute('aria-current','page');await expect(page.getByRole('link',{name:'문제 탐색',exact:true})).not.toHaveAttribute('aria-current');await expect(page.getByRole('button',{name:'보고서 과제 시작',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'구현 과제 시작',exact:true})).toBeVisible();await page.getByLabel('과제 모드').selectOption('SIMULATION');await page.getByRole('button',{name:'구현 과제 시작',exact:true}).click();await expect(page).toHaveURL(/\/learn\/[0-9a-f-]+$/);await page.getByRole('button',{name:'2. 작업',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.screenshot({path:test.info().outputPath('mobile.png'),fullPage:true});});

test('guided work preserves drafts across desktop/mobile panels and does not submit on navigation',async({page,context,request})=>{
 const who=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,who.session);
 const res=await request.post(`${apiBase}/learning-flows`,{headers:who.headers,data:{requestKey:crypto.randomUUID(),kind:'CODING',mode:'TRAINING'}});expect(res.ok()).toBeTruthy();const flow=await res.json();
 await page.goto(`/learn/${flow.id}`);await expect(page.getByLabel('훈련 안내')).toContainText('시작 코드를 테스트');
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();await page.getByLabel('solution.js',{exact:true}).fill('// unsaved draft');await page.getByLabel('AI에게 요청',{exact:true}).fill('아직 전송하지 않은 질문');expect(await page.getByLabel('AI 대화 패널',{exact:true}).evaluate(element=>element.scrollTop)).toBe(0);expect(await page.getByRole('region',{name:'AI와 함께 수정하기',exact:true}).evaluate(element=>element.scrollTop)).toBe(0);
 await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).fill('아직 저장하지 않은 설명');
 await page.getByRole('button',{name:'2. 작업',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toHaveValue('// unsaved draft');await expect(page.getByLabel('AI에게 요청',{exact:true})).toHaveValue('아직 전송하지 않은 질문');
 const panel=page.getByLabel('결과물 패널',{exact:true});const scroll=await panel.evaluate(e=>{e.scrollTop=90;return e.scrollTop;});expect(scroll).toBeGreaterThan(0);
 await page.getByRole('button',{name:'1. 과제 이해',exact:true}).click();await page.getByRole('button',{name:'2. 작업',exact:true}).click();expect(await panel.evaluate(e=>e.scrollTop)).toBe(scroll);
 await panel.evaluate(e=>{e.scrollTop=0;});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('desktop-work.png'),fullPage:true});
 await page.setViewportSize({width:375,height:850});await page.getByRole('navigation',{name:'작업 패널 선택'}).getByRole('button',{name:'AI 대화',exact:true}).click();await expect(page.getByLabel('AI에게 요청',{exact:true})).toHaveValue('아직 전송하지 않은 질문');await expect(page.getByLabel('solution.js',{exact:true})).not.toBeVisible();
 await page.getByRole('navigation',{name:'작업 패널 선택'}).getByRole('button',{name:'내 결과물',exact:true}).click();await expect(page.getByLabel('solution.js',{exact:true})).toHaveValue('// unsaved draft');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.evaluate(()=>window.scrollTo(0,400));const header=await page.getByRole('banner').boundingBox();const stages=await page.getByRole('navigation',{name:'단계 이동'}).boundingBox();expect(stages!.y).toBeGreaterThanOrEqual(header!.y+header!.height-1);
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('mobile-work.png'),fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'3. 검증·제출',exact:true}).click();await expect(page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true})).toHaveValue('아직 저장하지 않은 설명');
 expect(await page.getByLabel('무엇을 어떻게 확인했나요?',{exact:true}).evaluate(e=>{let n:HTMLElement|null=e;while(n){if(getComputedStyle(n).animationName!=='none')return false;n=n.parentElement;}return true;})).toBeTruthy();
 await page.reload();await expect(page.getByRole('button',{name:'3. 검증·제출',exact:true})).toHaveAttribute('aria-current','step');await page.goto('/learn');await expect(page.locator(`a[href="/learn/${flow.id}"]`)).toHaveAccessibleName(/검증·제출 이어가기/);
 expect((await (await request.get(`${apiBase}/learning-flows/${flow.id}`,{headers:who.headers})).json()).stage).toBe('WORKING');
});

test('successful feedback offers a focused reader and a complete permanent record',async({page,context,request})=>{
 const who=await testIdentity(request,`flow-${crypto.randomUUID()}`);await installTestSession(context,who.session);const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
 const task={kind:'REPORT',title:'결제 지연 상황을 동료에게 설명하기',situation:'관측 기록을 바탕으로 사실과 미확인 사항을 설명하세요.',requirements:['사실과 추정을 구분합니다.'],deliverable:'근거가 연결된 보고서',questions:['왜 이렇게 판단했나요?','조건이 바뀌면 무엇을 확인하나요?'],hints:['사실을 구분하세요.']};
 const source=(id:string,label:string,text:string)=>({id,label,text});
 const feedback={practiceArea:'VERIFY',items:[
  {area:'REQUEST',observation:'확인하려는 문제와 자료 범위를 AI에게 전달했습니다.',nextAction:'원하는 답변 형식도 함께 요청해 보세요.',recordIds:['request'],sources:[source('request','나의 요청','자료에서 확인된 사실과 아직 모르는 부분을 구분해 줘.')]},
  {area:'VERIFY',observation:'AI의 원인 제안을 원자료와 대조하고 미확인으로 남겼습니다.',nextAction:'외부 결제사 응답 시간도 확인해 보세요.',recordIds:['verification'],sources:[source('verification','사용자가 선택한 원문',JSON.stringify({materialId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',lineStart:4,lineEnd:4,quote:'10:07 기록에서 아직 수집하지 못한 지표를 확인했다.'}))]},
  {area:'IMPROVE',observation:'확인되지 않은 원인을 보고서에서 확정하지 않았습니다.',nextAction:'핵심 주장마다 근거 줄을 연결해 보세요.',recordIds:['artifact'],sources:[source('artifact','제출한 보고서','결제 지연은 관찰됐지만 원인은 아직 확인되지 않았다.')]},
  {area:'EXPLAIN',observation:'선택한 판단과 남은 한계를 자신의 말로 설명했습니다.',nextAction:'다른 가설을 배제할 조건을 덧붙여 보세요.',recordIds:['answer'],sources:[source('answer','나의 직접 설명','수집되지 않은 지표가 있어 원인을 확정하지 않았다.')]},
 ]};
 const flow={id,kind:'REPORT',mode:'TRAINING',flowVersion:'learning-flow-v1',sessionId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',codingId:null,parentId:null,stage:'FEEDBACK',version:4,notes:{explanation:'원인을 확정하지 않았다.',verification:'원자료를 대조했다.',citations:[{materialId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',lineStart:4,lineEnd:4}]},hints:[{index:0,text:'사실을 구분하세요.'}],snapshot:{artifact:'결제 지연은 관찰됐지만 원인은 아직 확인되지 않았다.',records:[],notes:{explanation:'원인을 확정하지 않았다.',verification:'원자료를 대조했다.',citations:[]},citations:[{materialId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',lineStart:4,lineEnd:4,quote:'외부 응답 시간은 아직 수집하지 못함.'}],artifactVersion:2,artifactHash:'a'.repeat(64),flowVersion:2,task,mode:'TRAINING',hints:[{index:0,text:'사실을 구분하세요.'}],cutoff:'2026-09-16T00:00:00Z'},answers:{decision:'원인을 확정하지 않았다.',change:'추가 지표를 확인한다.'},feedback,feedbackStatus:'SUCCEEDED',task,comparison:[]};
 await page.route(`${apiBase}/learning-flows/${id}`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(flow)}));
 await page.goto(`/learn/${id}`);const focused=page.locator('section[aria-labelledby="feedback-focus-heading"]');
 await expect(focused.getByRole('heading',{name:'문제와 요청 구체화',exact:true})).toBeVisible();const archive=page.getByRole('heading',{name:'전체 피드백',exact:true}).locator('xpath=ancestor::details[1]');const archiveSummary=archive.locator(':scope > summary');await expect(archive).not.toHaveAttribute('open','');await archiveSummary.click();await expect(archive.getByRole('button',{name:'집중해서 보기',exact:true})).toHaveCount(4);await archiveSummary.click();
 await focused.getByRole('button',{name:'다음 피드백',exact:true}).click();await expect(focused.getByRole('heading',{name:'제안 검증',exact:true})).toBeVisible();const sourceSummary=focused.locator('summary').filter({hasText:'사용자가 선택한 원문'});await expect(sourceSummary).toBeVisible();await expect(focused.getByText(/materialId/)).toHaveCount(0);await sourceSummary.click();await expect(focused.locator('details[open]>p').filter({hasText:'10:07 기록에서 아직 수집하지 못한 지표를 확인했다.'})).toBeVisible();
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:test.info().outputPath('feedback-focused-desktop.png'),fullPage:true});await page.setViewportSize({width:375,height:850});await page.evaluate(()=>window.scrollTo(0,0));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:test.info().outputPath('feedback-focused-mobile.png'),fullPage:true});
});
