package com.doezip.learning.adapter;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import java.util.*;
public class FlowFeedbackValidator {
 public JsonNode validate(JsonNode candidate,JsonNode input){
  if(!candidate.isObject()||candidate.size()!=2||!candidate.path("items").isArray()||candidate.path("items").size()!=4)throw new IllegalArgumentException("feedback shape");
  if(!candidate.has("practiceArea")||!Set.of("REQUEST","VERIFY","IMPROVE","EXPLAIN").contains(candidate.path("practiceArea").asText()))throw new IllegalArgumentException("practice priority");
  Map<String,JsonNode> records=new HashMap<>();input.path("records").forEach(r->records.put(r.path("id").asText(),r));Set<String> areas=new HashSet<>();
  var result=candidate.deepCopy();
  for(var item:result.path("items")){
   if(item.size()!=4||!item.has("area")||!item.has("observation")||!item.has("nextAction")||!item.has("recordIds")||!Set.of("REQUEST","VERIFY","IMPROVE","EXPLAIN").contains(item.path("area").asText())||!areas.add(item.path("area").asText()))throw new IllegalArgumentException("feedback area");
   for(String field:List.of("observation","nextAction"))if(!item.path(field).isTextual()||item.path(field).asText().isBlank()||item.path(field).asText().length()>2000)throw new IllegalArgumentException("feedback text");
   var ids=item.path("recordIds");if(!ids.isArray()||ids.isEmpty()||ids.size()>6)throw new IllegalArgumentException("missing evidence");
   var sources=((ObjectNode)item).putArray("sources");Set<String> seen=new HashSet<>();
   for(var id:ids){if(!id.isTextual()||!records.containsKey(id.asText())||!seen.add(id.asText()))throw new IllegalArgumentException("unknown evidence");sources.add(records.get(id.asText()));}
  }
  // Material and learner quotes are always copied from the frozen server record, not generated by the model.
  return result;
 }
}
